dataset:
  dataset_dir: /media/andrius/Extreme SSD/datasets
  dataset_prefix: MonoamineR_human_0_aug_no_Q96RJ0
  max_smiles_len: 100
model:
  d_emb: 384
  d_inner: 384
  d_model: 384
  n_head: 16
  n_layer: 6
trainer:
  batch_size: 32
  epochs: 100
  eval_every_n_batches: 2500
  lr: 0.0002
  save_every_n_batches: 100
